force-app/main/default/objects/Account/fields/Coordinating_Program__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the account to a specific cordinate program or parent entity; used to establish hierarchy, define billing responsibility, and manage program-based memberships.</description>
    <label>Coordinating Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Coordinating Program)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_PR_Created_From_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_PR_Created_From_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PR Created From Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Person_Email__c</fullName>
    <description>Stores primary email address; used as the main communication and login credential.</description>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Last_Name__c</fullName>
    <description>Stores last name; used in Person Account creation and identification.</description>
    <label>Primary Contact Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>Stores program category; identifies the type of program associated with the account (e.g., local program, coordinating program), and is used for segmentation, eligibility determination, reporting, and applying program-specific business rules.</description>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local Program</fullName>
            </value>
            <value>
                <fullName>Coordinating Program</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Sub Member</fullName>
                <isActive>false</isActive>
                <label>Sub Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>Stores membership end date; indicates expiration of membership.</description>
    <formula>IF(Membership__r.Is_Active__c , Membership__r.TermEndDate__c, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Term_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_Start_Date__c</fullName>
    <description>Stores membership start date; indicates beginning of membership lifecycle.</description>
    <formula>Membership__r.TermStartDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/Program_Relationship__c.object-meta.xml
<CustomObject>
    <label>Program Relationship</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Program Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Relationship__c/fields/Coordinating_Program__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program__c</fullName>
    <label>Coordinating Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Relationships</relationshipLabel>
    <relationshipName>Program_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Is_PR_Created_From_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_PR_Created_From_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PR Created From Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Local_Program__c.field-meta.xml
<CustomField>
    <fullName>Local_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Account should be a Local Program</errorMessage>
        <filterItems>
            <field>Account.Program_Type__c</field>
            <operation>equals</operation>
            <value>Local Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Relationships (Local Program)</relationshipLabel>
    <relationshipName>Program_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <inlineHelpText>Financially Supported: The CP pays for the LP.
Jurisdictional: The LP pays for itself.</inlineHelpText>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pays LP Membership</fullName>
            </value>
            <value>
                <fullName>Jurisdictional</fullName>
            </value>
            <value>
                <fullName>Financially Supported</fullName>
                <isActive>false</isActive>
                <label>Financially Supported</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Relationship Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramRelationshipTriggerTest.cls
@isTest
public class ProgramRelationshipTriggerTest {


    @isTest
    static void testBeforeInsertValid() {
        
        Id orgRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization Account').getRecordTypeId();

        Account cp = new Account(name = 'Cordinating Program',Program_Type__c = 'Coordinating Program',recordtypeId = orgRecordTypeId,Person_Last_Name__c = 'Tes LName');
        cp.Person_Email__c = 'test@test.com'; 
        insert cp;
        
        Account lp = new Account(name = 'Cordinating Program',Program_Type__c = 'Local Program',recordtypeId = orgRecordTypeId,Person_Last_Name__c = 'Tes LName');
        lp.Person_Email__c = 'test@test.com'; 
        lp.Coordinating_Program__c = cp.Id;
        insert lp;
        
        Test.startTest();
        Program_Relationship__c pr = new Program_Relationship__c(
            Local_Program__c = lp.Id,
            Coordinating_Program__c = cp.Id,
            Status__c = 'Active',
            Term_Start_Date__c = Date.today(),
            Term_End_Date__c = Date.today().addyears(1),
            Relationship_Type__c = 'Jurisdictional',
            Is_PR_Created_From_Account__c = false
        );
        insert pr;
        
        pr.Is_PR_Created_From_Account__c = true;
        update pr;
        
        Test.stopTest();
    }
    
    @isTest
    static void test2() {
        
        Id orgRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Organization Account').getRecordTypeId();

        Account cp = new Account(name = 'Cordinating Program',Program_Type__c = 'Coordinating Program',recordtypeId = orgRecordTypeId,Person_Last_Name__c = 'Tes LName');
        cp.Person_Email__c = 'test@test.com'; 
        insert cp;
        
        Account lp = new Account(name = 'Cordinating Program',Program_Type__c = 'Local Program',recordtypeId = orgRecordTypeId,Person_Last_Name__c = 'Tes LName');
        lp.Person_Email__c = 'test@test.com'; 
        lp.Coordinating_Program__c = cp.Id;
        insert lp;
        
        Test.startTest();
        Program_Relationship__c pr = new Program_Relationship__c(
            Local_Program__c = lp.Id,
            Coordinating_Program__c = cp.Id,
            Status__c = 'Inactive',
            Term_Start_Date__c = Date.today(),
            Term_End_Date__c = Date.today().addyears(1),
            Relationship_Type__c = 'Jurisdictional',
            Is_PR_Created_From_Account__c = false
        );
        insert pr;
        
        pr.Status__c = 'Active';
        update pr;
        
        Program_Relationship__c pr1 = new Program_Relationship__c(
            Local_Program__c = lp.Id,
            Coordinating_Program__c = cp.Id,
            Status__c = 'Active',
            Term_Start_Date__c = Date.today(),
            Term_End_Date__c = Date.today().addyears(1),
            Relationship_Type__c = 'Jurisdictional',
            Is_PR_Created_From_Account__c = false
        );
        try{
            insert pr1;
        } catch (DmlException e){
            //System.assert(e.getMessage().contains('already related with another CP'), 'Expected LP already related error but got: ' + e.getMessage());
        }
        
        Test.stopTest();

    }

}