force-app/main/default/objects/Account/fields/Coordinating_Program__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the account to a specific cordinate program or parent entity; used to establish hierarchy, define billing responsibility, and manage program-based memberships.</description>
    <label>Coordinating Program</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Coordinating Program)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Coordinating_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program_Name__c</fullName>
    <description>Stores program name; used for reporting and identification.</description>
    <formula>Coordinating_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinating Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Term_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Term_End_Date__c</fullName>
    <description>Stores membership end date; indicates expiration of membership.</description>
    <formula>IF(Membership__r.Is_Active__c , Membership__r.TermEndDate__c, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Term End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/Program_Relationship__c.object-meta.xml
<CustomObject>
    <label>Program Relationship</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Program Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Relationship__c/fields/Coordinating_Program__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program__c</fullName>
    <label>Coordinating Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Relationships</relationshipLabel>
    <relationshipName>Program_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Coordinating_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Coordinating_Program_Name__c</fullName>
    <formula>Coordinating_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coordinating Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Local_Program__c.field-meta.xml
<CustomField>
    <fullName>Local_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local Program</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Account should be a Local Program</errorMessage>
        <filterItems>
            <field>Account.Program_Type__c</field>
            <operation>equals</operation>
            <value>Local Program</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Relationships (Local Program)</relationshipLabel>
    <relationshipName>Program_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Local_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Local_Program_Name__c</fullName>
    <formula>Local_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Local Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <inlineHelpText>Financially Supported: The CP pays for the LP.
Jurisdictional: The LP pays for itself.</inlineHelpText>
    <label>Relationship Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pays LP Membership</fullName>
            </value>
            <value>
                <fullName>Jurisdictional</fullName>
            </value>
            <value>
                <fullName>Financially Supported</fullName>
                <isActive>false</isActive>
                <label>Financially Supported</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Relationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Relationship Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProgramRelationshipTriggerHandler.cls
/**
 * Class ProgramRelationshipTriggerHandler
 *
 * Trigger Handler for the AccountContactRelation SObject. This class implements the TriggerInterface
 * interface to help ensure the trigger code is bulkified and all in one place.
 */
public with sharing class ProgramRelationshipTriggerHandler implements TriggerInterface
{	
	
    public Set<String> existingPairs;
    public Map<Id, Account> lps;
	// Constructor
	public ProgramRelationshipTriggerHandler()
	{
        existingPairs = new Set<String>();
        lps = new Map<Id, Account>();
	}

	/**
	 * bulkBefore
	 *
	 * This method is called prior to execution of a BEFORE trigger. Use this to cache
	 * any data required into maps prior execution of the trigger.
	 */
    
    public Map<Id,List<Program_Relationship__c>> prMap = new Map<Id,List<Program_Relationship__c>>();
	public void bulkBefore()
	{
        Set<Id> lpIds = new Set<Id>();
        Set<Id> cpIds = new Set<Id>();
        for (Program_Relationship__c pr : (List<Program_Relationship__c >)Trigger.new) {
            if (pr.Local_Program__c != null && pr.Coordinating_Program__c != null) {
                lpIds.add(pr.Local_Program__c);
                cpIds.add(pr.Coordinating_Program__c);
            }
        }
        if (!lpIds.isEmpty()) {
            lps = new Map<Id, Account>([SELECT Id, Coordinating_Program__c,Coordinating_Program__r.name FROM Account WHERE Id IN :lpIds]);
        }
        if (!lpIds.isEmpty() && !cpIds.isEmpty()) {
            
            for (Program_Relationship__c existing : [SELECT Local_Program__c,Local_Program__r.name, Coordinating_Program__c,Coordinating_Program__r.name,Relationship_Type__c,Term_End_Date__c,Coordinating_Program_Name__c,Local_Program_Name__c FROM Program_Relationship__c WHERE Local_Program__c IN :lpIds AND Coordinating_Program__c IN :cpIds AND Status__c = 'Active' AND Term_End_Date__c != null]) {
                existingPairs.add(existing.Local_Program__c + '-' + existing.Coordinating_Program__c);
                if(!prMap.containskey(existing.Coordinating_Program__c)){
                    List<Program_Relationship__c> prlist = new List<Program_Relationship__c>();
                    prlist.add(existing);
                    prMap.put(existing.Coordinating_Program__c,prlist);
                }else{
                    prMap.get(existing.Coordinating_Program__c).add(existing);
                }
                
            }
        }    
	}
	
	public void bulkAfter()
	{ 
        Set<Id> lpIds = new Set<Id>();
        for (Program_Relationship__c pr : (List<Program_Relationship__c >)Trigger.new) {
            if (pr.Local_Program__c != null && pr.Coordinating_Program__c != null ) {
                lpIds.add(pr.Local_Program__c);
            }
        }
        
        if (!lpIds.isEmpty()) {
            lps = new Map<Id, Account>([SELECT Id, Coordinating_Program__c,Coordinating_Program__r.name FROM Account WHERE Id IN :lpIds and Coordinating_Program__c = null]);
        }
            
	}
    
	public void beforeInsert(SObject so)
	{
        Program_Relationship__c pr = (Program_Relationship__c)so;
        
        if(pr.Coordinating_Program__c != null && prMap.containskey(pr.Coordinating_Program__c)){
            for(Program_Relationship__c existing : prMap.get(pr.Coordinating_Program__c)){
                if(pr.Local_Program__c <> null && pr.Local_Program__c == existing.Local_Program__c && pr.Coordinating_Program__c == existing.Coordinating_Program__c &&  pr.Relationship_Type__c == existing.Relationship_Type__c && pr.Term_End_Date__c <> null &&  pr.Term_End_Date__c.year() == existing.Term_End_Date__c.year()){
                    //pr.addError('The LP (' + pr.Local_Program_Name__c + ') is already related with the CP (' + pr.Coordinating_Program_Name__c + ') for this term year : ' +pr.Term_End_Date__c.year());
                }
            }
        }
		
		if(pr.Local_Program__c <> null && lps.containskey(pr.Local_Program__c) && lps.get(pr.Local_Program__c).Coordinating_Program__c <> null && pr.Coordinating_Program__c <> lps.get(pr.Local_Program__c).Coordinating_Program__c ){
			//pr.adderror('The LP ('+ pr.Local_Program_Name__c + ') is already related with another CP  ('+ lps.get(pr.Local_Program__c).Coordinating_Program__r.name + ') for this term year : '+pr.Term_End_Date__c.year());
		}
	}
	
	public void beforeUpdate(SObject oldSo, SObject so)
	{
        Program_Relationship__c pr = (Program_Relationship__c)so;
        Program_Relationship__c oldPr = (Program_Relationship__c)oldSo;
        
        if(pr.Status__c == 'Active' && pr.Status__c <> oldPr.Status__c &&  pr.Coordinating_Program__c != null && prMap.containskey(pr.Coordinating_Program__c)){
            for(Program_Relationship__c existing : prMap.get(pr.Coordinating_Program__c)){
                if(pr.Local_Program__c <> null && pr.Local_Program__c == existing.Local_Program__c && pr.Coordinating_Program__c == existing.Coordinating_Program__c &&  pr.Relationship_Type__c == existing.Relationship_Type__c && pr.Term_End_Date__c <> null &&  pr.Term_End_Date__c.year() == existing.Term_End_Date__c.year()){
                    //pr.addError('The LP (' + pr.Local_Program_Name__c + ') is already related with the CP (' + pr.Coordinating_Program_Name__c + ') for this term year : ' +pr.Term_End_Date__c.year());
                }
            }
        }
		
		if(pr.Local_Program__c <> null && lps.containskey(pr.Local_Program__c) && pr.Coordinating_Program__c <> lps.get(pr.Local_Program__c).Coordinating_Program__c){
			//pr.adderror('The LP ('+ pr.Local_Program_Name__c + ') is already related with another CP  ('+ lps.get(pr.Local_Program__c).Coordinating_Program__r.name + ') for this term year : '+pr.Term_End_Date__c.year());
		}
	}
	
	/**
	 * beforeDelete
	 *
	 * This method is called iteratively for each record to be deleted during a BEFORE
	 * trigger.
	 */
	public void beforeDelete(SObject so)
	{	
		
	}
	List<Account> accToBeUpdated = new List<Account>();
	public void afterInsert(SObject so)
	{
        Program_Relationship__c pr = (Program_Relationship__c)so;
        if(pr.Coordinating_Program__c <> null && pr.Local_Program__c <> null && lps.containskey(pr.Local_Program__c) && lps.get(pr.Local_Program__c).Coordinating_Program__c == null){
            Account acc = lps.get(pr.Local_Program__c);
            acc.Coordinating_Program__c = pr.Coordinating_Program__c;
            accToBeUpdated.add(acc);
        }
	}
    
	
	public void afterUpdate(SObject oldSo, SObject so)
	{
    	Program_Relationship__c pr = (Program_Relationship__c)so;
        Program_Relationship__c oldPr = (Program_Relationship__c)oldSo;
        if(pr.Status__c == 'Active' && pr.Status__c <> oldPr.Status__c && pr.Local_Program__c <> null && lps.containskey(pr.Local_Program__c) && lps.get(pr.Local_Program__c).Coordinating_Program__c == null){
            Account acc = lps.get(pr.Local_Program__c);
            acc.Coordinating_Program__c = pr.Coordinating_Program__c;
            accToBeUpdated.add(acc);
        }
	}
	
	public void afterDelete(SObject so)
	{
        
	}
	
	/**
	 * andFinally
	 *
	 * This method is called once all records have been processed by the trigger. Use this 
	 * method to accomplish any final operations such as creation or updates of other records.
	 */
	public void andFinally(){
        if(!accToBeUpdated.isempty()){
            update accToBeUpdated;
        }
	}   
}