force-app/main/default/objects/Account/fields/Max_Sub_Members__c.field-meta.xml
<CustomField>
    <fullName>Max_Sub_Members__c</fullName>
    <description>Shows members count that are reached on account, count only Admin, Primary contact, sub-member roles from ACR.</description>
    <formula>Membership__r.Membership_Type__r.Max_Sub_Members__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Sub Members Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores linked membership; central to membership lifecycle tracking and direct check about memberships</description>
    <label>Membership</label>
    <referenceTo>Memberships__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <description>Stores membership category; used for classification and reporting.</description>
    <formula>Membership__r.Membership_Type__r.Name</formula>
    <label>Membership Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Orgnanization_Email__c.field-meta.xml
<CustomField>
    <fullName>Orgnanization_Email__c</fullName>
    <description>Stores organization’s primary email address; used for official communication. (This can be organization email or primary contact email).</description>
    <label>Organization Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Person_Last_Name__c</fullName>
    <description>Stores last name; used in Person Account creation and identification.</description>
    <label>Primary Contact Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <description>Stores program category; identifies the type of program associated with the account (e.g., local program, coordinating program), and is used for segmentation, eligibility determination, reporting, and applying program-specific business rules.</description>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Local Program</fullName>
            </value>
            <value>
                <fullName>Coordinating Program</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Sub Member</fullName>
                <isActive>false</isActive>
                <label>Sub Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization_Account.recordType-meta.xml
<RecordType>
    <fullName>Organization_Account</fullName>
    <active>true</active>
    <label>Organization Account</label>
</RecordType>

force-app/main/default/objects/Membership_Type__c/Membership_Type__c.object-meta.xml
<CustomObject>
    <label>Membership Type</label>
    <nameField>
        <label>Membership Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membership Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership_Type__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field denotes the particular type whether it is active or not</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership_Type__c/fields/Max_Sub_Members__c.field-meta.xml
<CustomField>
    <fullName>Max_Sub_Members__c</fullName>
    <label>Max Sub Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership_Type__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The monetary value associated with the benefit.</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Memberships__c/Memberships__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>MBR-{0000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Memberships__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Stores a description or category about membership details.</description>
    <label>Description</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Main St State Coordinator Pkg</fullName>
            </value>
            <value>
                <fullName>Designated Paid by CP non-def</fullName>
            </value>
            <value>
                <fullName>Allied Mbrs General Join/Renew</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Memberships__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Defines the membership type in membership; used for reporting and showing which type of membership is this.</description>
    <label>Membership Type</label>
    <referenceTo>Membership_Type__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Memberships__c/fields/TermStartDate__c.field-meta.xml
<CustomField>
    <fullName>TermStartDate__c</fullName>
    <description>Stores the date when the membership term begins; used to determine active period.</description>
    <label>Term Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/AccountContactRelationTrigger_Test.cls
@isTest
public class AccountContactRelationTrigger_Test {

     /* ----------------------------------------------------------
       Test Setup – reusable data for all test methods
       ---------------------------------------------------------- */
    @testSetup
    static void setupData() {
        
        // Standard Pricebook
        Id stdPb = Test.getStandardPricebookId();
        Pricebook2 pb = new Pricebook2(Id = stdPb, IsActive = true);
        update pb;
        
        // Membership Type
        Membership_Type__c memType = new Membership_Type__c(Name = 'Gold', Max_Sub_Members__c = 10, IsActive__c=true, Description__c='test', Price__c = 100);
        insert memType;

        // Membership
        Memberships__c membership = new Memberships__c(Membership_Type__c = memType.Id, TermStartDate__c = Date.today());
        insert membership;

        Id personRtId;
        Id orgRtId;
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName();

        if (rtMap.containsKey('PersonAccount')) {
            personRtId = rtMap.get('PersonAccount').getRecordTypeId();
        }
        if (rtMap.containsKey('Organization_Account')) {
            orgRtId = rtMap.get('Organization_Account').getRecordTypeId();
        }
        
        // Account
        List<Account> accList = new List<Account>();
        Account acc = new Account(LastName = 'Testing', Membership__c = membership.Id, RecordTypeId = personRtId, personEmail = 'testAcc101@gmail.com');
        Account acc1 = new Account(LastName = 'Testing2', Membership__c = membership.Id, RecordTypeId = personRtId, personEmail = 'testAcc102@gmail.com');
        accList.add(acc);
        accList.add(acc1);
        Account acct = new Account(Name = 'org Test', Program_Type__c = 'Coordinating Program', Person_Last_Name__c = 'pc-cont',
                                   Orgnanization_Email__c  = 'test101@gmail.com', Membership__c = membership.Id, RecordTypeId = orgRtId);
        accList.add(acct);
        insert accList;
    }
	/* ----------------------------------------------------------
       Test: Insert ACR within max limit
       ---------------------------------------------------------- */
    @IsTest
    static void testInsertACRWithinLimit() {
		Account personAcc = [SELECT Id, PersonContactId FROM Account WHERE IsPersonAccount = true LIMIT 1];
        Account acc = [SELECT Id FROM Account WHERE IsPersonAccount = false LIMIT 1];
		
        Test.startTest();

        AccountContactRelation acr = new AccountContactRelation(AccountId = acc.Id, ContactId = personAcc.PersonContactId, Roles = 'Primary Contact');
        insert acr;

        Test.stopTest();
    }
	
    @IsTest
    static void testAfterUpdate_PrimaryContactSwap() {
        
        List<Account> personAcc = [SELECT Id, PersonContactId FROM Account WHERE IsPersonAccount = true LIMIT 2];
        Account acc = [SELECT Id FROM Account WHERE IsPersonAccount = false LIMIT 1];

        AccountContactRelation acr = new AccountContactRelation(AccountId = acc.Id, ContactId = personAcc[0].PersonContactId, Roles = 'Primary Contact');
        insert acr;
        
        AccountContactRelation acrToUpdate = new AccountContactRelation(AccountId = acc.Id,
            ContactId = personAcc[1].PersonContactId,
            Roles = 'Admin'
        );
        insert acrToUpdate;

        Test.startTest();
		AccountContactRelation acrToBeUpdated = [select id from AccountContactRelation where roles = 'admin' limit 1];
        acrToBeUpdated.Roles = 'Primary Contact';
        update acrToBeUpdated;
		
        Test.stopTest();
    }
    
	@IsTest
    static void deleteACR(){
        List<Account> personAcc = [SELECT Id, PersonContactId FROM Account WHERE IsPersonAccount = true LIMIT 2];
        Account acc = [SELECT Id FROM Account WHERE IsPersonAccount = false LIMIT 1];

        AccountContactRelation acr = new AccountContactRelation(AccountId = acc.Id, ContactId = personAcc[0].PersonContactId, Roles = 'Primary Contact');
        insert acr;
        
        AccountContactRelation acrToUpdate = new AccountContactRelation(AccountId = acc.Id,
            ContactId = personAcc[1].PersonContactId,
            Roles = 'Admin'
        );
        insert acrToUpdate;
        AccountContactRelation acrDelete = [SELECT Id, AccountId FROM AccountContactRelation LIMIT 1];

        Test.startTest();
        delete acrDelete;
        Test.stopTest();
    }
}