force-app/main/default/objects/Error__c/Error__c.object-meta.xml
<CustomObject>
    <description>This is used to store error logs in code</description>
    <label>Error</label>
    <nameField>
        <label>Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error__c/fields/API_Request__c.field-meta.xml
<CustomField>
    <fullName>API_Request__c</fullName>
    <label>API Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error__c/fields/API_Response__c.field-meta.xml
<CustomField>
    <fullName>API_Response__c</fullName>
    <label>API Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error__c/fields/Error_Trace__c.field-meta.xml
<CustomField>
    <fullName>Error_Trace__c</fullName>
    <label>Error Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error__c/fields/Error_Type__c.field-meta.xml
<CustomField>
    <fullName>Error_Type__c</fullName>
    <label>Error Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ErrorLoggingApex.cls
public class ErrorLoggingApex {
    public static Error__c createErrorLog(String errorType, String subject, String requestBody, String responseBody, String statusCode, Exception ex) {
        Error__c errorLog = new Error__c();
        errorLog.Error_Type__c = errorType;
        errorLog.Subject__c = subject;
        errorLog.API_Request__c = requestBody;
        errorLog.API_Response__c = responseBody;
        errorLog.Description__c = 'An error occurred during the External Reviewer Sync job. See other fields for details.';
        
        if (ex != null) {
            errorLog.Name = ex.getTypeName();
            errorLog.Error_Message__c = ex.getMessage();
            errorLog.Error_Trace__c = ex.getStackTraceString();
        } else {
            errorLog.Name = 'HTTP Status Code Error';
            errorLog.Error_Message__c = 'The endpoint returned a non-success status code: ' + statusCode;
        }
        return errorLog;
    }
}